title = "Les couleurs dans Adobe Illustrator"

description = """\
Illustrator gère les couleurs des modèles RVB et CMJN. \
Il est important de bien régler le modèle voulu en fonction du support. \
Ce module montre comment.\
"""
