title = "Mise en scène de la carte dans Illustrator"

description = """\
Ce module explique comment concrètement habiller une carte thématique \
à l'aide d'Adobe Illustrator, en ajoutant la titraille, les toponymes \
et finalement les autres éléments d'habillage.
"""
