title = "Construire la légende dans Illustrator"

description = """\
Explication sur comment construire une légende dans Illustrator \
pour une carte choroplèthe et une carte en symboles proportionnels \
(ou une carte en symboles proportionnels colorés).\
"""
