title = "Modèles de couleur"

description = """\
Explication des deux modèles de couleurs, \
le modèle RVB basé sur la lumière et utilisé pour les écrans, \
et le modèle CMYK utilisé en imprimerie.\
"""
