title = "Création du fond de carte"

description = """\
La première étape du TP1 consiste en la création du fond de carte \
avec Adobe Illustrator. Ce module montre comment créer ce fond de carte \
à l'aide de ce logiciel.\
"""
