title = "Techniques de représentation cartographique"

description = """\
La sémiologie graphique définit les règles pour représenter \
des données de nature différentes à l'aide des variables visuelles appropriées.\
"""
